env:
  global:
  - TERM=dumb
language: node_js
node_js:
- "node"
- 6
- 7
- 8
- 9
- lts/*
install: true
before_script:
- sudo apt update -y || true
- sudo apt install --no-install-recommends -y curl
- curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
- echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt update -y || true
- sudo apt install --no-install-recommends -y yarn
- yarn global add npm-check-updates
script:
  - export root=$(pwd)
  - >
    for path in \
      first-blood \
      _starter \
    ; do
      cd "$root/$path"
      #
      yarn -i
      yarn predeploy
      yarn postdeploy
      if [ -f npm-debug.log ]; then cat npm-debug.log; fi
      #
      ncu
      ncu -u
      yarn -i
      yarn upgrade
      if [ -f npm-debug.log ]; then cat npm-debug.log; fi
    done;
cache:
  directories:
  - node_modules
  - $HOME/.npm
